sprite $centreon [48x48/16] {
FFFFFFFFFFFFFFFFFFFFFFBBBBBBAAAAFFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFCCCBBBBBBBBAAAAAFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFCCCCCCBBBBBBBBAAAAAAFFFFFFFFFFFFF
FFFFFFFFFFFFFCCCCCCCCCBBBFFFFFAAAAAFFFFFFFFFFFFF
FFFFFFFFFFFFCCCCCCCCFFFFFFFFFFFFAAAAFFFFFFFFFFFF
FFFFFFFFFFDCCCCCCFFFFFFFFFFFFFFFAAAAFFFFFFFFFFFF
FFFFFFFFFDDDDCCFFFFFFFFFFFFFFFF99999FFFFFFFFFFFF
FFFFFFFFDDDDDFFFFFFFFF8888999999999FFFFFFFFFFFFF
FFFFFFFDDDDDFFFFFFF888888889999999FFFFFFFFFFFFFF
FFFFFFDDDDDFFFFFF7888888889999999FFFFFFFFFFFFFFF
FFFFFDDDDDFFFFF777888888FFFFFFFFFFFFFFFFFFFFFFFF
FFFFDDDDDFFFFF7777778FFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFEDEDDFFFFF777777FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFEEEEFFFFF77777FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFEEEEEFFFF77777FFFFFFFF66666FFFFFFFFFFFFFFFFFFF
FFEEEEFFFF77777FFFFFF666666666FFFFFFFFFFFFFFFFFF
FEEEEEFFFF6777FFFFFF666666666FFFFFFFFFFFFFFFFFFF
FEEEEFFFF66667FFFFF6666669FFFFFFFFFFFFFFFFFFFFFF
FEEEEFFFF6666FFFFF66666FFFFFFFFFFFFFFFFFFFFFFFFF
EEEEFFFF66666FFFF66666FFFFFFFFFFFFFFFFFFFFFFFFFF
EEEEFFFF6666FFFFF6666FFFFFFFFFFFFFFFFFFFFFFFFFFF
EEEEFFFF6666FFFF66666FFFFFFFFFFFFFFFFFFFFFFFFFFF
EEEEFFFF6666FFFF6666FFFFFFFFFFFFFFFFFFFFFFFFFFFF
EEEEFFFF6666FFFF6666FFFFFFFFFFFFFFFFFFFFFFFFFFFF
EEEEFFFF6666FFFF6666FFFFFFFFFFFFFFFFFFFFFFFFFFFF
EEEEFFFF6666FFFF6666FFFFFFFFFFFFFFFFFFFFFFFFFFFF
EEEEFFFF6666FFFF96666FFFFFFFFFFFFFFFFFFFFFFFFFFF
EEEEFFFF6666FFFFF6666FFFFFFFFFFFFFF6666666FFFFFF
FEEEEFFFB6666FFFF66666FFFFFFFFFFFF666666666FFFFF
FEEEEFFFF6556FFFFF66666FFFFFFFFF666666666666FFFF
FEEEEFFFF55555FFFFF6666666FFF66666666FFF6666FFFF
FEEEEEFFFF5555FFFFFF6666666666666666FFFF6666FFFF
FFEEEEFFFF55555FFFFFFF666666666666FFFFFF6666FFFF
FFEEEEEFFFF55555FFFFFFFF66666666FFFFFFFF6666FFFF
FFFEEEEFFFFF55555FFFFFFFFFFFFFFFFFFFFF566666FFFF
FFF9EEEEFFFFF555555FFFFFFFFFFFFFFFFFF555555FFFFF
FFFFEEEEEFFFFF5555555FFFFFFFFFFFFFF5555555FFFFFF
FFFFFEEEEEFFFFF6555555555FFFFFF555555555FFFFFFFF
FFFFFFEEEEEFFFFFF5555555555555555555555FFFFFFEEF
FFFFFFFEEEEEFFFFFFF55555555555555555FFFFFFFEEEEE
FFFFFFFFEEEEEEFFFFFFFF55555555555FFFFFFFFFEEEEEE
FFFFFFFFFEEEEEEFFFFFFFFFFFFFFFFFFFFFFFFFEEEEEEEF
FFFFFFFFFFEEEEEEEEFFFFFFFFFFFFFFFFFFFFEEEEEEEFFF
FFFFFFFFFFFFEEEEEEEEEFFFFFFFFFFFFFFEEEEEEEEEFFFF
FFFFFFFFFFFFFFEEEEEEEEEEEEEEEEEEEEEEEEEEEEFFFFFF
FFFFFFFFFFFFFFFFEEEEEEEEEEEEEEEEEEEEEEEEFFFFFFFF
FFFFFFFFFFFFFFFFFFFEEEEEEEEEEEEEEEEEEFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFEEEEEEEEEEFFFFFFFFFFFFFFF
}
