@startuml
sprite $liferay [48x48/4] {
2AggggggggggggggggggggggggggggggggggggggggggggA2
gggggggggggggggggggggggggggggggggggggggggggggggg
gggggggaWWWWWWggWWWWWWWggWWWWWWWgggggggggggggggg
ggggggg0000000gg0000000gg0000000gggggggggggggggg
ggggggg2222222gg2222222gg2222222gggggggggggggggg
gggggggWWWWWWWggWWWWWWWggggggggggfWWWWWWWggggggg
ggggggg0000000gg0000000ggggggggggg0000000ggggggg
ggggggg2222222gg2222222ggggggggggg2222222ggggggg
gggggggWWWWWWWgggggggggggWWWWWWWggWWWWWWWggggggg
ggggggg0000000ggggggggggg0000000gg0000000ggggggg
ggggggg2222222Qgggggggggg2222222gg2222222ggggggg
ggggggggggggggggWWWWWWWggWWWWWWWggWWWWWWWggggggg
gggggggggggggggg0000000gg0000000gg0000000ggggggg
gggggggggggggggg2222222gg2222222gg2222226ggggggg
gggggggggggggggggggggggggggggggggggggggggggggggg
WeggggggggggggggggggggggggggggggggggggggggggggeW
}

@enduml