@startuml
sprite $liferay [48x48/4] {
2AFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFA2
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
FFFFFFFaWWWWWWFFWWWWWWWFFWWWWWWWFFFFFFFFFFFFFFFF
FFFFFFF0000000FF0000000FF0000000FFFFFFFFFFFFFFFF
FFFFFFF2222222FF2222222FF2222222FFFFFFFFFFFFFFFF
FFFFFFFWWWWWWWFFWWWWWWWFFFFFFFFFFfWWWWWWWFFFFFFF
FFFFFFF0000000FF0000000FFFFFFFFFFF0000000FFFFFFF
FFFFFFF2222222FF2222222FFFFFFFFFFF2222222FFFFFFF
FFFFFFFWWWWWWWFFFFFFFFFFFWWWWWWWFFWWWWWWWFFFFFFF
FFFFFFF0000000FFFFFFFFFFF0000000FF0000000FFFFFFF
FFFFFFF2222222QFFFFFFFFFF2222222FF2222222FFFFFFF
FFFFFFFFFFFFFFFFWWWWWWWFFWWWWWWWFFWWWWWWWFFFFFFF
FFFFFFFFFFFFFFFF0000000FF0000000FF0000000FFFFFFF
FFFFFFFFFFFFFFFF2222222FF2222222FF2222226FFFFFFF
FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
WeFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFeW
}

@enduml